services:
- postgresql
- mysql
- elasticsearch
- rabbitmq
addons:
  apt:
    sources:
    - elasticsearch-5.x
    packages:
    - elasticsearch
    - oracle-java8-set-default
stages:
- lint
- test
- deploy
env:
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD:
cache: pip
before_install:
- pip install --upgrade pip setuptools wheel
- bash -xe travis/before-install.sh
install:
- pip install -r requirements-dev.txt


.test_job: &test_job
  language: python
  stage: test
  script:
  - coverage run --include='pacifica/*' -m pytest -v
  - coverage report --show-missing --fail-under 100
  - if [[ $CODECLIMATE_REPO_TOKEN ]] ; then codeclimate-test-reporter ; fi
  - pip install .
  - python setup.py bdist_wheel
  - python setup.py sdist

.lint_job: &lint_job
  language: python
  stage: lint
  script:
  - pre-commit run -a
  - radon cc pacifica

.deploy_job: &deploy_job
  language: python
  stage: deploy
  script: skip

jobs:
  include:
  - <<: *lint_job
    python: 3.6
  - <<: *lint_job
    python: 2.7
  - <<: *test_job
    python: 3.6
  - <<: *test_job
    python: 2.7
  - <<: *deploy_job
    python: 3.6
  - <<: *deploy_job
    python: 2.7

deploy:
  skip_cleanup: true
  provider: pypi
  user: dmlb2000
  distributions: sdist bdist_wheel
  password:
    secure: hutFNsqElsyDgL+nGObpRWgCAiNf6YH+v4c0uqZUPYd6TbjKNbnsjCQS/GXbC6/1poa4WvxNuol4Xx/Yw74xcQyb993xu/sC8SqKeTQsWIxtR0ZJEsDoQzzwzVufmlk2bYsOvfVBbJY3pHGjvobVkuDAQc9EpaOqIHxPgWFK8geDTN/2k5pAqn2RyKinBF2RPfe27wEl4E9gSyxt0tzZCSV5uSWxZZ5jUXabk5+c3psrDl+wIEqrr68moUnmygXNWXbsWQhnJSjCznXDfcFAuVnLisUudjIcDH1Wi8jC4w4cVBj+w00W3ZGV/b5wN6YrNSeR7hV6BGrqBk+L1cmflVbdNGel4vGhqNmL5rTxje9tdOqzl/5eCBP0yHxNQrdECiRK4nUGuYITYb22DXO1jY9fpsEFVQNAzkfygm8vmnAhfrNQHXi2AdN/fL2ZPmGyHFl6KaXie2CU2z2U2j1jIVcx1ySTHwCzmNxpbkfxmjiOwil128dm5y3i+UKUodRiCbgVuDddf3jjOiy9OiilvpIp4n6tbEji1JkNsd8ptKGSejtMxUakXiZwZ0Lu+sN3lVjH0kiBfQGrhfXxzMDeB72RgrvDNLMz6mmc988AcwgASPcTae76xsE0aTYE4fHz2T67Yy7AZe1za7go6QzdeHnUBb60KrhzaB2Tc57jI+A=
  on:
    tags: true
